/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thora.core.flamesofthora;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
